### ISSUE TITLE
links

### ISSUE THREAD

**Issue by rabia-aaziz** [Maria-khurshid/Test-May-9#5]
apnay default style sheet ka link tamam links k end mai or head tag k closing say pehlay dalain
for example:
<head>
yahan saray links aa gai or end mai default stylesheet ka link aagaya
 <link rel="stylesheet" href="style.css">
</head>

https://github.com/Maria-khurshid/Test-May-9/blob/ff2d1f1bfedf0646f2a08b17649a3e0c8086c1c1/index.html#L12

**Comment by Maria-khurshid** [comment]
resolved

**Comment by Maria-khurshid** [comment]
I added new html file.
